# Generated by Django 6.0.4 on 2026-04-28 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('owner_name', models.CharField(blank=True, max_length=180)),
                ('template', models.CharField(choices=[('minimarket', 'Minimarket'), ('cafe', 'Kafe'), ('service', 'Servis'), ('wholesale', 'Ulgurji savdo')], default='minimarket', max_length=32)),
                ('currency', models.CharField(default='UZS', max_length=8)),
                ('starting_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
