# Generated by Django 6.0.4 on 2026-04-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('unit', models.CharField(default='dona', max_length=32)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business', 'sku')},
            },
        ),
    ]
