# Generated by Django 6.0.4 on 2026-04-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=180)),
                ('direction', models.CharField(choices=[('receivable', 'Olinadigan'), ('payable', 'Beriladigan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='businesses.business')),
            ],
            options={
                'ordering': ['is_closed', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Savdo'), ('income', 'Kirim'), ('expense', 'Chiqim'), ('debt', 'Qarz'), ('inventory', 'Ombor')], max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(blank=True, max_length=80)),
                ('linked_to', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('happened_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='businesses.business')),
            ],
            options={
                'ordering': ['-happened_at', '-created_at'],
            },
        ),
    ]
